import { Inter } from "next/font/google";
import { type Metadata } from "next";

import type { TLayoutProps } from "types";
import JotaiProvider from "@/lib/providers/jotai-provider";
import Navbar from "@/components/navbar";
import "@/styles/globals.css";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Appwrite demo",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: TLayoutProps) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <JotaiProvider>
          <Navbar />
          <main>{children}</main>
        </JotaiProvider>
      </body>
    </html>
  );
}
